kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
     name: product-azure-disk
     namespace: k8-org
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: product-mssql-data
  namespace: k8-org  
  annotations:
    volume.beta.kubernetes.io/storage-class: product-azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi